"""add group table

Revision ID: 63bc38386fc1
Revises: 3842cd23d54a
Create Date: 2025-05-16 19:21:16.390203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bc38386fc1'
down_revision: Union[str, None] = '3842cd23d54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('chat_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'groups', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'chat_id')
    # ### end Alembic commands ###
